export type SpacingsTypes =
  | 'padding'
  | 'paddingTop'
  | 'paddingBottom'
  | 'paddingRight'
  | 'paddingLeft'
  | 'px'
  | 'py'
  | 'margin'
  | 'marginTop'
  | 'marginBottom'
  | 'marginRight'
  | 'marginLeft'
  | 'mx'
  | 'my'
  | 'gap'
  | 'rowGap'
  | 'columnGap'
